const menuItemObj = [
      [
            {
                  id: "1",
                  title: "Buttermilk Pancakes",
                  price: "15$",
                  img: "images/item-1.jpeg",
                  text: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
                  category: "breakfast",
            },
            {
                  id: "2",
                  title: "Diner Double",
                  price: "15$",
                  img: "images/item-2.jpeg",
                  text: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
                  category: "breakfast",
            },
            {
                  id: "3",
                  title: "Godzilla Milkshake",
                  price: "$7",
                  img: "images/item-3.jpeg",
                  text: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
                  category: "breakfast",
            },
            {
                  id: "4",
                  title: "Country Delight",
                  price: "15$",
                  img: "images/item-4.jpeg",
                  text: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
                  category: "breakfast",
            },
            {
                  id: "5",
                  title: "Egg Attack",
                  price: "15$",
                  img: "images/item-5.jpeg",
                  text: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
                  category: "lunch",
            },
            {
                  id: "6",
                  title: "Oreo Dream",
                  price: "15$",
                  img: "images/item-6.jpeg",
                  text: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
                  category: "lunch",
            },
            {
                  id: "7",
                  title: "Bacon Overflow",
                  price: "15$",
                  img: "images/item-7.jpeg",
                  text: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
                  category: "lunch",
            },
            {
                  id: "8",
                  title: "American Classic",
                  price: "15$",
                  img: "images/item-8.jpeg",
                  text: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
                  category: "shakes",
            },
            {
                  id: "9",
                  title: "Quarantine Buddy",
                  price: "15$",
                  img: "images/item-9.jpeg",
                  text: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
                  category: "dinner",
            },
            {
                  id: "10",
                  title: "Bison Steak",
                  price: "15$",
                  img: "images/item-10.jpeg",
                  text: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed",
                  category: "dinner",
            },
      ],
];
